default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Distribute to Beta track"
  lane :beta do
    gradle(
          task: "bundle",
          build_type: "Release",
          print_command: false,
          properties: {
            "android.injected.signing.store.file" => "/Users/andrehitchman/learning-projects/android-projects/key/brightboy/bright-boy-keystore.jks",
            "android.injected.signing.store.password" => "8ZC1Zc^@w4m",
            "android.injected.signing.key.alias" => "BrightBoy",
            "android.injected.signing.key.password" => "8ZC1Zc^@w4m",
            })
    upload_to_play_store(
          track: 'beta',
            skip_upload_metadata: 'true',
            skip_upload_apk: 'true',
            skip_upload_images: 'true',
            skip_upload_screenshots: 'true',
          )
  end

end
