name: Android Emulator Workflow

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/*/master'
  workflow_dispatch:

jobs:
  run_ui_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Android SDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Print Environment
        run: |
          echo "Available Tools:"
          ls -l /usr/bin
          echo "PATH: $PATH"

      - name: Download and Extract Android SDK
        run: |
          echo "Workspace: ${{ github.workspace }}"
          ls -l $HOME
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          ls -l
          unzip sdk-tools-linux-4333796.zip -d $HOME/android-sdk
        env:
          HOME: ${{ github.workspace }}
          ANDROID_HOME: $HOME/android-sdk
          PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Create AVD and Start Emulator
        run: |
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force --name my_workflow_avd --package "system-images;android-30;default;armeabi-v7a" --abi armeabi-v7a
          $ANDROID_HOME/emulator/emulator -avd my_workflow_avd -no-window
