name: Check If Labeled

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/*'


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print match
        if: ${{ contains(github.event.*.labels.*.name, 'pre-release') }} && github.event.action == 'labeled' && github.event.action == 'synchronize'
        run: |
          echo "contains match: ${{ github.event.*.labels.*.name['pre-release'] }}"
        shell: bash