name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:
    branches:
      - 'main'
      - 'feature/*/main'

  workflow_dispatch:

jobs:

#  unit_tests:
#    runs-on: [ubuntu-latest]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Run Unit tests
#        run: ./gradlew test
#
#  android_tests:
#    runs-on: [ macos-latest ]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Java
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Generate Dev APK
#        run: ./gradlew assembleDebug
#
#      - name: List build output
#        if: always()
#        run: |
#          echo "Build outputs"
#          cd /home/runner/work/GitHubActionsPlayground/GitHubActionsPlayground/app/build/outputs/apk/debug/
#          tree -a
#
#      - name: Export build artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: dev-build
#          path: |
#            ${{ github.workspace }}/app/build/outputs/apk/debug/*.apk
#          retention-days: 3

  distribute_to_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Distribution Folder
        run: |
          distribution_folder=`sh ${{ github.workspace }}/.github/scripts/distribution_folder_name.sh -b "${{ github.ref }}"`
          echo "firefly-${distribution_folder}"
        shell: bash