name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:

#  unit_tests:
#    runs-on: [ubuntu-latest]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Run Unit tests
#        run: ./gradlew test
#
#  android_tests:
#    runs-on: [ macos-latest ]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Java
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#
#  build:
#    needs: [ unit_tests ]
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Generate Dev APK
#        run: ./gradlew assembleDebug
#
#      - name: List build output
#        if: always()
#        run: |
#          echo "Build outputs"
#          cd /home/runner/work/GitHubActionsPlayground/GitHubActionsPlayground/app/build/outputs/apk/debug/
#          tree -a
#
#      - name: Export build artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: dev-build
#          path: |
#            ${{ github.workspace }}/app/build/outputs/apk/debug/*.apk
#          retention-days: 3

  deploy:
#    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
#      - name: Download All Artifacts
#        uses: actions/download-artifact@v2
#
#      - name: Install AppCenter CLI
#        run: |
#          npm install -g appcenter-cli
#          echo "List downloads folder contents:"
#          ls -R
#        shell: bash
#      -  feature_name=$(${{ github.workspace }}.github/scripts/get_feature_name.sh -b "${{ github.ref }}")
#      -  echo "branch reference is: " $feature_name

      - name: Upload to Appcenter
        run: |
          ls -r
          ${{ github.workspace }}.github/scripts/get_feature_name.sh -b "${{ github.ref }}"
          echo "github ref: " ${{ github.ref }}
          echo $(pwd)
        shell: bash