name: Deploy to Beta

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/*/master'
  workflow_dispatch:

jobs:
  build_aab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate AAB
        run: ./gradlew clean assembleRelease

      - name: Export build artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-build
          path: |
            ${{ github.workspace }}/app/build/outputs/bundle/release/*.aab
          retention-days: 3


  fastlane:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download All Artifacts
        uses: actions/download-artifact@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies to support ruby project
        run: |
          bundle config --global set deploy_platform_default x86_64-linux
          bundle install

      - name: Configure Keystore
        run: |
          echo "$KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$KEY_STORE_KEY_PASSWORD" >> keystore.properties
          echo "storePassword=$KEY_STORE_PASSWORD" >> keystore.properties
          ls -R
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_STORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Build and distribute app
        run: |
          echo "$CONSOLE_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec fastlane beta
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_STORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          CONSOLE_CONFIG_JSON: ${{ secrets.PLAY_CONSOLE_CONFIG_JSON }}