name: Deploy Feature

on:
  push:
    branches:
      - main
      - feature/*

  workflow_dispatch:

jobs:

  build:
    name: Build Debug Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Generate Dev APK
        run: ./gradlew assembleDebug

      - name: List build output
        if: always()
        run: |
          echo "Build outputs"
          cd /home/runner/work/GitHubActionsPlayground/GitHubActionsPlayground/app/build/outputs/apk/debug/
          tree -a

      - name: Export build artifact
        uses: actions/upload-artifact@v2
        with:
          name: dev-build
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/debug/*.apk
          retention-days: 3

  deploy:
    name: Deploy Debug Build
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download All Artifacts
        uses: actions/download-artifact@v3

      - name: Get Build Information
        id: get-build-information
        run: |
          echo "Get Build Information"
          appCenterReleaseUrl="https://appcenter.ms/orgs/GithubTest/apps/GithubActionsApp/distribute/releases"
          versionName=$(./gradlew printProjectPropertyName -PconfigKey=versionName -q)
          versionCode=$(./gradlew printProjectPropertyName -PconfigKey=versionCode -q)
          minSdk=$(./gradlew printProjectPropertyName -PconfigKey=minSdk -q)
          targetSdk=$(./gradlew printProjectPropertyName -PconfigKey=targetSdk -q)

          {
            echo "=== Build Information ==="
            echo "| Name | Value |"
            echo "| ---- | ----- |"
          
            echo "| App Version Name | $versionName |"
            echo "| App Version Code | $versionCode |"
            echo "| App Min SDK | $minSdk |"
            echo "| App Target SDK | $targetSdk |"
            echo "| App Center Download Link | [Download Url]($appCenterReleaseUrl)"
            echo ""
          } >> GITHUB_STEP_SUMMARY

      - name: Generate Build Information Notes
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "releaseNotes<<$EOF" >> $STEP_BUILD_INFO_SUMMARY
          

      - name: Install AppCenter CLI
        run: |
          npm install -g appcenter-cli
          echo "List downloads folder contents:"
          ls -R
        shell: bash

      - name: Upload Debug Build to Appcenter
        run: |
          sh /home/runner/work/GitHubActionsPlayground/GitHubActionsPlayground/.github/scripts/app_center_release_notes.sh releaseNotes
          cat release_notes_markdown.md
          appcenter distribute groups publish -f ./dev-build/app-debug.apk --token ${{ secrets.APP_CENTER_TOKEN }} --app GithubTest/GithubActionsApp -g "Beta Testers" -R release_notes_markdown.md --debug
        shell: bash

      - name: Build Summary Notes
        run: |
          echo "### Build Notes" >> STEP_BUILD_INFO_SUMMARY