name: PR Checks

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

#  linting_checks:
#    runs-on: [ubuntu-latest]


  unit_tests:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit tests
        run: ./gradlew test