name: Simple Android Espresso Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  setup_and_build:
    name: Build and Test
    runs-on: ubuntu-latest # Using Ubuntu runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List output
        run: |
          echo "file path structure"
          tree -a

      - name: List Files in workspace
        run: |
          # List files in the github.workspace directory
          ls "${{ github.workspace }}"

      - name: Install Android SDK and Emulator
        run: |
          # Run the install_android.sh script
          chmod +x install_android.sh
          ${{ github.workspace }}./.github/scripts/install_android.sh
        timeout-minutes: 20 # Adjust as needed

      - name: Start Android Emulator
        run: |
          # Run the start_emulator.sh script
          chmod +x start_emulator.sh
          source $HOME/.bashrc # Load environment variables
          ${{ github.workspace }}/.github/scripts/start_emulator.sh
        timeout-minutes: 10 # Adjust as needed

      - name: Run Tests
        run: |
          # Your test commands here
        timeout-minutes: 30 # Adjust as needed

      - name: Stop Android Emulator
        run: |
          $ANDROID_SDK_ROOT/emulator/emulator -

